"""Bounding box diagnostics analysis for post-run review.

This script analyzes JSON Lines bbox log files generated by BboxDiagnosticsLogger
and provides human-readable summaries and metrics for debugging tracking issues.
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional


def load_bbox_log(filepath: str) -> List[Dict[str, Any]]:
    """Load all track observations from a bbox diagnostics JSON Lines file."""
    records = []
    try:
        with open(filepath, "r") as f:
            for line_num, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    continue
                try:
                    record = json.loads(line)
                    records.append(record)
                except json.JSONDecodeError as e:
                    print(f"Warning: Failed to parse line {line_num}: {e}", file=sys.stderr)
    except FileNotFoundError:
        print(f"Error: File not found: {filepath}", file=sys.stderr)
        return []
    return records


def analyze_bbox_log(records: List[Dict[str, Any]]) -> None:
    """Print analysis summary of bbox log records."""
    if not records:
        print("No records to analyze.")
        return

    # Group by track_id
    tracks: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for record in records:
        track_id = record.get("track_id")
        if track_id:
            tracks[track_id].append(record)

    # Get frame range
    frames = [r.get("frame_number", 0) for r in records]
    min_frame = min(frames) if frames else 0
    max_frame = max(frames) if frames else 0

    print(f"\n{'='*70}")
    print(f"Bounding Box Diagnostics Analysis")
    print(f"{'='*70}")
    print(f"Total frames: {max_frame - min_frame + 1} (frames {min_frame}-{max_frame})")
    print(f"Total track observations: {len(records)}")
    print(f"Unique tracks: {len(tracks)}")
    print(f"Avg observations per track: {len(records) / len(tracks):.1f}")
    print(f"\n{'Track ID':<20} {'Obs':<6} {'Frames':<30} {'Avg Vol (m³)':<15} {'Depth Range':<20}")
    print(f"{'-'*70}")

    for track_id in sorted(tracks.keys(), key=lambda x: int(x.split('_')[-1]) if '_' in x else 0):
        observations = tracks[track_id]
        frame_nums = sorted(set(o.get("frame_number", 0) for o in observations))
        frame_range = f"{frame_nums[0]}-{frame_nums[-1]}" if frame_nums else "?"

        volumes = [o.get("bbox_volume_m3", 0.0) for o in observations if o.get("bbox_volume_m3")]
        avg_volume = sum(volumes) / len(volumes) if volumes else 0.0

        depths_min = [o.get("depth_min_m", 0.0) for o in observations if o.get("depth_min_m")]
        depths_max = [o.get("depth_max_m", 0.0) for o in observations if o.get("depth_max_m")]
        depth_range_str = f"{min(depths_min):.2f}-{max(depths_max):.2f}m" if depths_min and depths_max else "N/A"

        print(f"{track_id:<20} {len(observations):<6} {frame_range:<30} {avg_volume:<15.3f} {depth_range_str:<20}")

    print(f"\n{'='*70}")
    print(f"Detailed Track Statistics")
    print(f"{'='*70}")

    for track_id in sorted(tracks.keys(), key=lambda x: int(x.split('_')[-1]) if '_' in x else 0):
        observations = tracks[track_id]
        frame_nums = sorted(set(o.get("frame_number", 0) for o in observations))

        volumes = [o.get("bbox_volume_m3", 0.0) for o in observations if o.get("bbox_volume_m3")]
        sizes = [o.get("bbox_3d_size", [0,0,0]) for o in observations if o.get("bbox_3d_size")]

        print(f"\n{track_id}:")
        print(f"  Observations: {len(observations)} across {len(set(frame_nums))} frames")
        print(f"  Frame span: {frame_nums[0]}-{frame_nums[-1]}")

        if volumes:
            print(f"  Volume: min={min(volumes):.3f}, max={max(volumes):.3f}, avg={sum(volumes)/len(volumes):.3f} m³")
            vol_range = (max(volumes) / min(volumes)) if min(volumes) > 0 else 0
            print(f"  Volume ratio (max/min): {vol_range:.2f}x")

        if sizes:
            print(f"  Size variations:")
            for i, dim_name in enumerate(["width", "depth", "height"]):
                dim_vals = [s[i] for s in sizes if len(s) > i]
                if dim_vals:
                    print(f"    {dim_name}: {min(dim_vals):.2f}-{max(dim_vals):.2f}m (range: {max(dim_vals)/max(min(dim_vals), 0.01):.2f}x)")

        # Check for fragmentation (large gap in frame numbers)
        if len(frame_nums) > 1:
            gaps = [frame_nums[i+1] - frame_nums[i] for i in range(len(frame_nums)-1)]
            if max(gaps) > 10:
                print(f"  ⚠️  Large frame gap detected: {max(gaps)} frames")
                gap_idx = gaps.index(max(gaps))
                print(f"     Gap between frame {frame_nums[gap_idx]} and {frame_nums[gap_idx+1]}")

    print(f"\n{'='*70}\n")


def main(log_file: str) -> None:
    """Load and analyze a bbox diagnostics log file."""
    records = load_bbox_log(log_file)
    analyze_bbox_log(records)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <bbox_log.jsonl>")
        print(f"\nAnalyze a bounding box diagnostics JSON Lines file.")
        sys.exit(1)

    log_file = sys.argv[1]
    main(log_file)
